//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int idFactura { get; set; }
        public System.DateTime fecha { get; set; }
        public int idOrden { get; set; }
        public int idCliente { get; set; }
        public int totalFactura { get; set; }
        public int idDescuentoTotal { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Descuetnos Descuetnos { get; set; }
        public virtual OrdenCompra OrdenCompra { get; set; }
    }
}
